import { countUsable, getDimension } from "./rubric.js";
import type { JudgedDimension, Scorecard, Verdict } from "./types.js";

/**
 * Pure rendering of a Scorecard to markdown and JSON. No LLM, no I/O — fully
 * unit-testable. The markdown is the human-facing artifact; the JSON is the
 * machine-readable form returned by the API and MCP server.
 */

/** A short, honest one-liner describing what each verdict means. */
const VERDICT_GLOSS: Record<Verdict, string> = {
  SHIPS: "Credible, reproducible, and close to deployable.",
  MIXED: "Real signal, but meaningful gaps or unproven claims remain.",
  THEATER: "Mostly demo theater; the strong claims are not backed.",
  INCONCLUSIVE: "Not enough usable evidence to score — no verdict asserted.",
};

function formatScore(score: number | null): string {
  return score === null ? "—" : `${score}`;
}

function dimensionRow(d: JudgedDimension): string {
  const dim = getDimension(d.dimension);
  const score = d.inconclusive ? "inconclusive" : formatScore(d.score);
  const confidence = d.inconclusive
    ? "—"
    : `${Math.round(d.confidence * 100)}%`;
  return `| ${dim.index} | ${dim.title} | ${dim.weight} | ${score} | ${confidence} |`;
}

/** Render a full scorecard to markdown. */
export function renderMarkdown(scorecard: Scorecard): string {
  const { usable, inconclusive } = countUsable(scorecard.dimensions);
  const overall = formatScore(scorecard.overallScore);

  const lines: string[] = [];

  lines.push(`# Ship or Theater — Scorecard`);
  lines.push("");
  lines.push(
    `**Verdict:** ${scorecard.verdict} — ${VERDICT_GLOSS[scorecard.verdict]}`,
  );
  lines.push("");
  lines.push(
    `**Reality score:** ${overall}${scorecard.overallScore === null ? "" : " / 100"}`,
  );
  lines.push("");
  lines.push(`**Claim:** ${scorecard.input.claim}`);
  if (scorecard.input.context && scorecard.input.context.trim().length > 0) {
    lines.push("");
    lines.push(`**Context:** ${scorecard.input.context}`);
  }
  if (scorecard.input.sourceUrl) {
    lines.push("");
    lines.push(`**Source:** ${scorecard.input.sourceUrl}`);
  }
  lines.push("");
  lines.push(`## Summary`);
  lines.push("");
  lines.push(scorecard.summary);
  lines.push("");

  lines.push(`## Dimensions`);
  lines.push("");
  lines.push(`| # | Dimension | Weight | Score | Confidence |`);
  lines.push(`|---|-----------|--------|-------|------------|`);
  for (const d of scorecard.dimensions) {
    lines.push(dimensionRow(d));
  }
  lines.push("");
  lines.push(
    `_${usable} of ${scorecard.dimensions.length} dimensions scored; ${inconclusive} inconclusive (excluded from the weighted mean)._`,
  );
  lines.push("");

  lines.push(`### Per-dimension reasoning`);
  lines.push("");
  for (const d of scorecard.dimensions) {
    const dim = getDimension(d.dimension);
    const label = d.inconclusive
      ? "inconclusive"
      : `${formatScore(d.score)}/100`;
    lines.push(`- **${dim.title}** (${label}): ${d.reasoning}`);
  }
  lines.push("");

  lines.push(`## Strongest steelman (best case FOR)`);
  lines.push("");
  lines.push(scorecard.strongestSteelman);
  lines.push("");

  lines.push(`## Strongest debunk (best case AGAINST)`);
  lines.push("");
  lines.push(scorecard.strongestDebunk);
  lines.push("");

  if (scorecard.assertions.length > 0) {
    lines.push(`## Extracted assertions`);
    lines.push("");
    for (const a of scorecard.assertions) {
      const tag = a.testable ? "testable" : "not directly testable";
      lines.push(`- [${a.id}] ${a.text} _(${tag})_`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(
    `_Generated by ship-or-theater using ${scorecard.model} at ${scorecard.generatedAt}._`,
  );

  return lines.join("\n");
}

/** Serialize a scorecard to canonical JSON. */
export function toJSON(scorecard: Scorecard, pretty = true): string {
  return JSON.stringify(scorecard, null, pretty ? 2 : 0);
}
